version: "3.8"

services:
  db:
    image: postgres:14.1-alpine
    restart: always
    ports:
      - "5435:5432"
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

volumes:
  db:
