import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "@/app/styles/globals.css";
import { Toaster } from "sonner";
import { Providers } from "@/app/providers/Providers";

const inter = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Finance",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Toaster />

        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
